-- HOA Secure Vote - Supabase PostgreSQL schema
-- Run this entire file once in Supabase Dashboard -> SQL Editor.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null,
  password_hash text not null,
  role text not null check (role in ('admin','voter')),
  full_name text not null,
  block text,
  lot text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists users_username_lower_uq on public.users (lower(username));
create index if not exists idx_users_role on public.users(role);
create index if not exists idx_users_block_lot on public.users(block,lot);

create table if not exists public.sessions (
  token_hash text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  csrf_token text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_sessions_user on public.sessions(user_id);
create index if not exists idx_sessions_expiry on public.sessions(expires_at);

-- Voters are restricted to one active login session at a time.
-- The user-row lock serializes concurrent login attempts so two devices cannot both
-- create sessions at the same moment. Admin accounts are intentionally exempt.
create or replace function public.hoa_enforce_single_voter_session()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  account_role text;
begin
  select role into account_role
  from public.users
  where id = NEW.user_id
  for update;

  if account_role is null then
    raise exception 'User account not found.';
  end if;

  -- Remove this user's expired sessions before checking for an active one.
  delete from public.sessions
  where user_id = NEW.user_id
    and expires_at <= now();

  if account_role = 'voter' and exists (
    select 1 from public.sessions
    where user_id = NEW.user_id
      and expires_at > now()
  ) then
    raise exception 'This voter account is already signed in on another device. Please log out there first before signing in here.';
  end if;

  return NEW;
end;
$$;

drop trigger if exists trg_single_voter_session on public.sessions;
create trigger trg_single_voter_session
before insert on public.sessions
for each row execute function public.hoa_enforce_single_voter_session();

-- Migration cleanup: remove expired sessions and, if an older deployment already
-- allowed multiple voter sessions, keep only the newest active session per voter.
delete from public.sessions where expires_at <= now();
with ranked_voter_sessions as (
  select s.token_hash,
         row_number() over (partition by s.user_id order by s.created_at desc, s.token_hash desc) as rn
  from public.sessions s
  join public.users u on u.id = s.user_id
  where u.role = 'voter'
)
delete from public.sessions s
using ranked_voter_sessions r
where s.token_hash = r.token_hash
  and r.rn > 1;

create table if not exists public.login_attempts (
  id bigint generated by default as identity primary key,
  ip text not null,
  username text not null,
  attempted_at timestamptz not null default now()
);
create index if not exists idx_login_attempts_ip_time on public.login_attempts(ip,attempted_at);

create table if not exists public.elections (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  status text not null default 'draft' check (status in ('draft','open','closed')),
  created_by bigint not null references public.users(id),
  opened_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_elections_status on public.elections(status);
create unique index if not exists one_open_election_uq on public.elections ((status)) where status='open';

create table if not exists public.positions (
  id bigint generated by default as identity primary key,
  election_id bigint not null references public.elections(id) on delete cascade,
  title text not null,
  seats integer not null default 1 check (seats between 1 and 50),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(election_id,title)
);
create index if not exists idx_positions_election on public.positions(election_id,sort_order);

create table if not exists public.candidates (
  id bigint generated by default as identity primary key,
  position_id bigint not null references public.positions(id) on delete cascade,
  full_name text not null,
  statement text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(position_id,full_name)
);
create index if not exists idx_candidates_position on public.candidates(position_id,sort_order);

-- Identity is deliberately stored separately from anonymous ballot choices.
create table if not exists public.voter_participation (
  user_id bigint not null references public.users(id) on delete restrict,
  election_id bigint not null references public.elections(id) on delete cascade,
  voted_at timestamptz not null default now(),
  receipt_code text not null unique,
  primary key(user_id,election_id)
);
create index if not exists idx_participation_election on public.voter_participation(election_id,voted_at);

create table if not exists public.ballots (
  id uuid primary key,
  election_id bigint not null references public.elections(id) on delete cascade,
  submitted_at timestamptz not null default now()
);
create index if not exists idx_ballots_election on public.ballots(election_id,submitted_at);

create table if not exists public.ballot_votes (
  ballot_id uuid not null references public.ballots(id) on delete cascade,
  election_id bigint not null references public.elections(id) on delete cascade,
  position_id bigint not null references public.positions(id) on delete cascade,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  primary key(ballot_id,candidate_id)
);
create index if not exists idx_ballot_votes_results on public.ballot_votes(election_id,position_id,candidate_id);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id bigint references public.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_audit_time on public.audit_log(created_at);

-- Keep direct browser access closed. The Cloudflare Worker uses a Supabase secret key.
alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.login_attempts enable row level security;
alter table public.elections enable row level security;
alter table public.positions enable row level security;
alter table public.candidates enable row level security;
alter table public.voter_participation enable row level security;
alter table public.ballots enable row level security;
alter table public.ballot_votes enable row level security;
alter table public.audit_log enable row level security;

revoke all on table public.users, public.sessions, public.login_attempts, public.elections,
  public.positions, public.candidates, public.voter_participation, public.ballots,
  public.ballot_votes, public.audit_log from anon, authenticated;

grant select, insert, update, delete on table public.users, public.sessions, public.login_attempts,
  public.elections, public.positions, public.candidates, public.voter_participation,
  public.ballots, public.ballot_votes, public.audit_log to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Passwords are bcrypt-hashed inside PostgreSQL, keeping expensive password hashing off
-- the Cloudflare Free Worker CPU budget.
create or replace function public.hoa_create_user(
  p_username text,
  p_password text,
  p_role text,
  p_full_name text,
  p_block text default null,
  p_lot text default null
) returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  new_id bigint;
begin
  if p_role not in ('admin','voter') then raise exception 'Invalid user role.'; end if;
  if length(coalesce(p_password,'')) < 8 then raise exception 'Password is too short.'; end if;
  insert into public.users(username,password_hash,role,full_name,block,lot,active)
  values(trim(p_username), crypt(p_password, gen_salt('bf',10)), p_role, trim(p_full_name), p_block, p_lot, true)
  returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.hoa_verify_login(p_username text, p_password text)
returns table(id bigint, username text, role text, full_name text, block text, lot text, active boolean)
language sql
security definer
set search_path = public, extensions
as $$
  select u.id,u.username,u.role,u.full_name,u.block,u.lot,u.active
  from public.users u
  where lower(u.username)=lower(trim(p_username))
    and u.active=true
    and u.password_hash = crypt(p_password,u.password_hash)
  limit 1;
$$;

create or replace function public.hoa_reset_password(p_user_id bigint, p_password text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if length(coalesce(p_password,'')) < 8 then raise exception 'Password is too short.'; end if;
  update public.users
  set password_hash=crypt(p_password,gen_salt('bf',10)), updated_at=now()
  where id=p_user_id and role='voter';
  if not found then return false; end if;
  delete from public.sessions where user_id=p_user_id;
  return true;
end;
$$;

-- Database-side ballot transaction. Either all ballot records are committed or none are.
create or replace function public.hoa_submit_ballot(
  p_user_id bigint,
  p_election_id bigint,
  p_ballot_id uuid,
  p_receipt_code text,
  p_selections jsonb
) returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  entry record;
  pos_id bigint;
  allowed_seats integer;
  selected_count integer;
  distinct_count integer;
  valid_count integer;
  total_selected integer := 0;
begin
  if not exists(select 1 from public.users where id=p_user_id and role='voter' and active=true) then
    raise exception 'Voter account is not active.';
  end if;
  if not exists(select 1 from public.elections where id=p_election_id and status='open') then
    raise exception 'This election is not open.';
  end if;
  if exists(select 1 from public.voter_participation where user_id=p_user_id and election_id=p_election_id) then
    raise exception 'This voter account has already submitted a ballot.';
  end if;
  if jsonb_typeof(p_selections) <> 'object' then raise exception 'Invalid ballot.'; end if;

  for entry in select * from jsonb_each(p_selections)
  loop
    if entry.key !~ '^[0-9]+$' or jsonb_typeof(entry.value) <> 'array' then
      raise exception 'Ballot contains an invalid position.';
    end if;
    pos_id := entry.key::bigint;
    select seats into allowed_seats from public.positions where id=pos_id and election_id=p_election_id;
    if allowed_seats is null then raise exception 'Ballot contains an invalid position.'; end if;

    selected_count := jsonb_array_length(entry.value);
    if selected_count > allowed_seats then raise exception 'Too many selections for a position.'; end if;
    if selected_count = 0 then continue; end if;

    select count(*), count(distinct v::bigint)
      into selected_count, distinct_count
    from jsonb_array_elements_text(entry.value) as x(v)
    where v ~ '^[0-9]+$';
    if selected_count <> jsonb_array_length(entry.value) or distinct_count <> selected_count then
      raise exception 'Ballot contains invalid or duplicate candidate selections.';
    end if;

    select count(*) into valid_count
    from public.candidates c
    where c.position_id=pos_id
      and c.id in (select v::bigint from jsonb_array_elements_text(entry.value) as x(v));
    if valid_count <> selected_count then raise exception 'Ballot contains an invalid candidate selection.'; end if;
    total_selected := total_selected + selected_count;
  end loop;

  if total_selected < 1 then raise exception 'Select at least one candidate before submitting.'; end if;

  insert into public.voter_participation(user_id,election_id,receipt_code)
  values(p_user_id,p_election_id,p_receipt_code);
  insert into public.ballots(id,election_id) values(p_ballot_id,p_election_id);

  for entry in select * from jsonb_each(p_selections)
  loop
    pos_id := entry.key::bigint;
    insert into public.ballot_votes(ballot_id,election_id,position_id,candidate_id)
    select p_ballot_id,p_election_id,pos_id,v::bigint
    from jsonb_array_elements_text(entry.value) as x(v);
  end loop;
  return p_receipt_code;
exception
  when unique_violation then
    raise exception 'This voter account has already submitted a ballot.';
end;
$$;

-- Prevent ballot configuration changes after voting opens, even if an API bug occurs.
create or replace function public.hoa_guard_position_changes()
returns trigger language plpgsql set search_path=public as $$
declare eid bigint;
begin
  if TG_OP = 'DELETE' then eid := OLD.election_id; else eid := NEW.election_id; end if;
  if current_setting('hoa.allow_election_delete', true) <> 'on' and exists(select 1 from public.elections where id=eid and status <> 'draft') then
    raise exception 'Positions are locked once voting opens.';
  end if;
  if TG_OP = 'DELETE' then return OLD; else return NEW; end if;
end; $$;

drop trigger if exists trg_guard_positions on public.positions;
create trigger trg_guard_positions before insert or update or delete on public.positions
for each row execute function public.hoa_guard_position_changes();

create or replace function public.hoa_guard_candidate_changes()
returns trigger language plpgsql set search_path=public as $$
declare pid bigint; eid bigint;
begin
  if TG_OP = 'DELETE' then pid := OLD.position_id; else pid := NEW.position_id; end if;
  select election_id into eid from public.positions where id=pid;
  if current_setting('hoa.allow_election_delete', true) <> 'on' and exists(select 1 from public.elections where id=eid and status <> 'draft') then
    raise exception 'Candidates are locked once voting opens.';
  end if;
  if TG_OP = 'DELETE' then return OLD; else return NEW; end if;
end; $$;

drop trigger if exists trg_guard_candidates on public.candidates;
create trigger trg_guard_candidates before insert or update or delete on public.candidates
for each row execute function public.hoa_guard_candidate_changes();

-- Permanently delete any election and all election-scoped data.
-- This is intended for administrator-controlled cleanup (including test elections).
-- The local setting allows the cascade to pass configuration-lock triggers without weakening normal edits.
create or replace function public.hoa_delete_election(p_election_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  e public.elections%rowtype;
  position_ids bigint[];
  candidate_ids bigint[];
begin
  select * into e from public.elections where id=p_election_id;
  if not found then raise exception 'Election not found.'; end if;
  select coalesce(array_agg(id), '{}'::bigint[]) into position_ids
  from public.positions where election_id=p_election_id;
  select coalesce(array_agg(c.id), '{}'::bigint[]) into candidate_ids
  from public.candidates c join public.positions p on p.id=c.position_id
  where p.election_id=p_election_id;

  -- Remove audit entries tied only to this test election so deleted test runs do not
  -- remain in the application's election history/audit trail.
  delete from public.audit_log
  where (entity_type='election' and entity_id=p_election_id::text)
     or (entity_type='position' and entity_id in (select x::text from unnest(position_ids) as t(x)))
     or (entity_type='candidate' and entity_id in (select x::text from unnest(candidate_ids) as t(x)))
     or details->>'electionId'=p_election_id::text;

  perform set_config('hoa.allow_election_delete','on',true);
  delete from public.elections where id=p_election_id;

  return jsonb_build_object('id',e.id,'title',e.title,'status',e.status,'deleted',true);
end;
$$;

revoke execute on function public.hoa_create_user(text,text,text,text,text,text) from public, anon, authenticated;
revoke execute on function public.hoa_verify_login(text,text) from public, anon, authenticated;
revoke execute on function public.hoa_reset_password(bigint,text) from public, anon, authenticated;
revoke execute on function public.hoa_submit_ballot(bigint,bigint,uuid,text,jsonb) from public, anon, authenticated;
revoke execute on function public.hoa_delete_election(bigint) from public, anon, authenticated;
grant execute on function public.hoa_create_user(text,text,text,text,text,text) to service_role;
grant execute on function public.hoa_verify_login(text,text) to service_role;
grant execute on function public.hoa_reset_password(bigint,text) to service_role;
grant execute on function public.hoa_submit_ballot(bigint,bigint,uuid,text,jsonb) to service_role;
grant execute on function public.hoa_delete_election(bigint) to service_role;
